name: Units CI

on: [push, pull_request]

jobs:
  test:
    name: Unit-Tests QA
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm i
      - run: npm run lint
      - run: npm run test-coverage

      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: test-report.html
        path: ./test-report.html
